# 服务配置
server:
  port: 8989

spring:
  profiles:
    active: dev
  application:
    name: dxblog
  freemarker:
    enabled: true
    cache: false
    suffix: .ftl
    charset: UTF-8

# actuator
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
