## 服务配置
server:
  port: 8989
spring:
  application:
    name: dxblog
  cache:
    cache-names: ehcache
    ehcache:
      config: ehcache.xml
  freemarker:
    enabled: true
    cache: false
    suffix: .ftl
    charset: UTF-8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dxblog
# application
application:
  version: @project.version@
# actuator
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# httpclient
httpclient:
  maxTotal: 100
  maxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
